const LISTFLIP = {
  LOADING: 'LISTFLIP_LOADING',
  FETCH_SUCCESS: 'LISTFLIP_FETCH_SUCCESS',
  FETCH_FAILED: 'LISTFLIP_FETCH_FAILED',
};

const DETAILFLIP = {
  LOADING: 'DETAILFLIP_LOADING',
  FETCH_DETAIL_SUCCESS: 'DETAILFLIP_FETCH_DETAIL_SUCCESS',
  RESET_DETAIL: 'DETAILFLIP_RESET_DETAIL',
};

export { LISTFLIP, DETAILFLIP };
